config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

  mount Ckeditor::Engine => '/ckeditor'
  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index'
  
  get 'jobs' => 'pages#jobs'
  resources :jobs, only: [:show]
  resources :feedbacks
  resources :pages, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :deliveries
  post '/delivery/get_price' => 'deliveries#get_price', as: :get_price
  resources :news, only: [:index, :show]
  get 'contacts' => 'pages#contacts'
  get 'delivery' => 'pages#delivery'
  
  get 'products' => 'pages#products'
  get 'page/:id' => 'pages#show'
  
  get 'factories' => 'factories#index', as: :factories
  get 'factory/:id' => 'factories#show', as: :factory

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    can :manage, :all
    can :import, [Delivery]
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  def before_import_save(record)
  end
end

app/models/factory_oil.rb
class FactoryOil < ActiveRecord::Base
  has_many :product_relations
  has_many :products, :through => :product_relations
  validates :name, :fullname, :about, :address, :image, presence: true
  scope :active, -> { where is_active: true }
  scope :on_main, -> { where is_main: true }

  DEFAULT_AVATAR = 'demo/_blank.png'
  has_attached_file :image,
                    styles: { small: '250x150>', medium: '220x280#', thumb: '100x125#' },
                    default_url: DEFAULT_AVATAR,
                    url: '/system/:class/:id/:style/:basename.:extension',
                    path: ':rails_root/public/system/:class/:id/:style/:basename.:extension'

  validates_attachment_content_type :image, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :text, presence: true
  scope :active, -> { where is_active: true }
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  def type_of
    [['Главное меню', 0],['Меню подвала',1]]
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  validates :title, :announce, presence: true
  scope :active, -> { where is_active: true }

end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :name, :uri, :text, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  has_many :product_relations
  has_many :factory_oils, :through => :product_relations
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  
  def before_import_save(record)
    p record
    p "------" 
    
    if !ProductCategory.exists?(name: record[:product_category])
      ProductCategory.create name: record[:product_category], is_active: true
    end
  end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  validates :name, presence: true
  scope :active, -> { where is_active: true }  
  has_many :products, dependent: :destroy
end

app/models/product_relation.rb
class ProductRelation < ActiveRecord::Base
  belongs_to :product
  belongs_to :factory_oil
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  add_breadcrumb "Вакансии", :jobs_path

  def show
    @job = Job.find params[:id]
    add_breadcrumb @job.title if @job

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  add_breadcrumb "Новости компании", :news_index_path
  def index
    @news = News.all.active.order('created_at desc')
  end
  def show
    @news = News.find_by_id! params[:id]
    add_breadcrumb @news.title if @news
  end 
  private
   def news_params
      params.require(:news).permit(:created_at)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by_uri!(params[:id])
    add_breadcrumb @page.name if @page
  end

  def contacts
    add_breadcrumb "Контакты"
  end
  
  def jobs
    add_breadcrumb "Карьера"
    @jobs = Job.all.active
  end
  
  def delivery
    add_breadcrumb "Доставка"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @factories = FactoryOil.all.active.on_main
    @news = News.all.active.order('id desc').limit(3)
    
    @from_city = Delivery.all.group(:from)
    @to_city = Delivery.all.group(:to)
    @trucks = Delivery.all.group(:truck)
    
    first_order_summ = Delivery.where("`to` = ? AND `from`= ? AND `truck` = ?",
    @to_city.first.to , @from_city.first.from, @trucks.first.truck).first
    
    @first_order_summ= first_order_summ ? first_order_summ.price_ton.to_i * first_order_summ.truck.to_i : 0
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_main_menu
    menu = Page.find_by_uri(:main_menu)
    menu.text.html_safe if menu
  end
  def get_footer_menu
    footer = Page.find_by_uri(:footer_menu)
    footer.text.html_safe if footer
  end
  def setting
    Setting.first! 
  end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_carousel.html.erb
<div class="jcarousel-wrapper">
  <div class="jcarousel">
    <ul>
      <li>
        <div class="bg"></div>
        <%= image_tag "car2.jpg", class: "img-slider slide1" %>
        <p class="photo-credits">
          <span class="title">Тритон Трейд</span>
          <br/>
          <span class="slogan">Доставляем хорошее топливо по низким ценам</span>
        </p>
      </li>
      <li>
        <div class="bg"></div>
        <%= image_tag "car3.jpg", class: "img-slider slide1" %>
        <p class="photo-credits">
          <span class="title">Тритон Трейд</span>
          <br/>
          <span class="slogan">Мы стараемся быть ближе к нашим клиентам</span>
        </p>
      </li>
      <li>
        <div class="bg"></div>
        <%= image_tag "car1.jpg", class: "img-slider slide1" %>
        <p class="photo-credits">
          <span class="title">Тритон Трейд</span>
          <br/>
          <span class="slogan">Мы доставляем только качественное топливо</span>
        </p>
      </li>
    </ul>
  </div>
  <div class="jcarousel-pagination"></div>
</div>

app/views/welcome/_factories.html.erb
<section class="wrapper">
  <div class="factories">
    <h1 class="title">Заводы</h1>
    <div class="jcarousel-wrapper-responsive">
      <div class="jcarousel-responsive">
        <ul>
          <% @factories.each do |f| %>
            <%= content_tag "li", link_to(image_tag(f.image.url(:small), class: "img-slider"), factory_path(f.id)) %>
          <% end %>
        </ul>
      </div>
      <a class="jcarousel-responsive-control-prev" href="#"></a>
      <a class="jcarousel-responsive-control-next" href="#"></a>
    </div>
  </div>
</section>

app/views/welcome/_feedback.html.erb
<h1>Свяжитесь
<br/>
с нами сегодня!</h1>
<%= form_for Feedback.new, remote: true  do |f| %>
<%= f.hidden_field :the_type, value: :feedback %>
<div class="form">
	<div class="submit_status notice" style="text-align: left;"></div>
	<div class="line">
		<%= f.text_field :title, class: 'inp-text', placeholder: "Имя",  required: true%>
	</div>
	<div class="line">
		<%= f.text_field :email, class: 'inp-text', placeholder: "E-mail", required: true%>
	</div>
	<div class="line">
		<%= f.text_field :phone, class: 'inp-text', placeholder: "Телефон",  required: true %>
	</div>
	<div class="line">
		<%= f.text_area :text, class: 'inp-text', placeholder: "Тексе сообщения", required: true %>
	</div>
	<div class="line line-send">
		<%= f.submit "Отправить", class: "btn2" %>
	</div>
</div>
<% end %>

app/views/welcome/_map.html.erb
<section class="wrapper map">
	<div id="map"></div>
	<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>
	<script>
		ymaps.ready(function() {
			var myMap = new ymaps.Map('map', {
				center : [55.8314,49.2055],
				zoom : 16
			}),
			    myPlacemark = new ymaps.Placemark([55.83160882223887, 49.195623177276495], {
				hintContent : 'ООО Тритон Трейд'
			}, {
				iconLayout : 'default#image',
				// Своё изображение иконки метки.
				iconImageHref : '/assets/marker.png',
				// Размеры метки.
				iconImageSize : [150, 150],
				// Смещение левого верхнего угла иконки относительно
				// её "ножки" (точки привязки).
				iconImageOffset : [-75, -75]
			});
			myMap.geoObjects.add(myPlacemark);
		});
	</script>
	<div class="bg"></div>
	<div class="right">
		<div class="info">
			<% info = Page.find_by_uri("map-company-information") %>
			<%= info.text.html_safe if info %>
		</div>
		<div class="form-box">
			<%= render partial: "feedback" %>
		</div>
	</div>
</section>
<div class="clear"></div>

app/views/welcome/_news.html.erb
<section class="wrapper news">
    <h1 class="title">Новости компании</h1>
    <div class="news-container">
        <% @news.each do |news| %>
            <div class="item">
                <h1><%= news.title %></h1>
                <div class="announce"><%= news.announce.html_safe %></div>
                <div class="clearfix"></div>
                <br/>
                <div class="more"><%=link_to "Подробнее &#187;".html_safe, news_path(news.id) %></div>
                <div class="date"><%= news.created_at.strftime("%d.%m.%Y") %></div>
              <div class="clearfix"></div>
            </div>
        <% end %>
      <div class="clearfix"></div>
      <%= link_to "Cмотреть все", news_index_path(), class: 'news-btn btn2' %>
    </div>
</section>

app/views/welcome/_order.html.erb
<section class="wrapper order-container">
  <h1 class="title">Рассчитать заявку</h1>
  <div class="order-box">
    <div class="form-container">
	<%= form_for Delivery.new, url: get_price_path(), remote: true do |f| %>

        <div class="item padding15">
          <span class="numeric">
            1
            <span class="v-sp"></span>
          </span>
          <span class="caption">
            Откуда
            <span class="g-sp g-sp1"></span>
          </span>
			<%= f.collection_select(:from, @from_city, :from, :from, {}, {class: "custom-select"} )  %>
		      
        </div>
        <div class="clear"></div>
        <div class="item padding15">
          <span class="numeric">
            2
            <span class="v-sp"></span>
          </span>
          <span class="caption">
            Куда
            <span class="g-sp g-sp2"></span>
          </span>
 			<%= f.collection_select(:to, @to_city, :to, :to, {}, {class: "custom-select"} )  %>
             
        </div>
        <div class="clear"></div>
        <div class="item padding15">
          <span class="numeric">3</span>
          <span class="caption">
            Бензовоз
            <span class="g-sp g-sp3"></span>
          </span>
		<%= f.collection_select :truck, @trucks, :truck, :truck, {}, {class: "custom-select"} %>

        </div>
      <% end %> 
    </div>
    <div class="x-line"></div>
    <div class="result-order">
      <h1>Стоимость доставки составит</h1>
      <div class="sum-result">~
        <span class="digit"><%= @first_order_summ.to_s.sub(/\d{2}/, '\& ')%></span>
      </div>
      <div class="info">
        Более подробнее <br/>уточняйте у менеджера
        <br><span class="phone-number"><%= setting.order_phone %></span>
      </div>
    </div>
  </div>
</section>

app/views/welcome/index.html.erb
<%= render partial: 'carousel' %>
<section class="wrapper">
	<div class="icons-container">

		<div class="item">
			<a href="/products"> <figure class="ico fuel"></figure>
			<figcaption>
				Топливо
			</figcaption> </a>
		</div>

		<div class="item">
			<a href="/delivery"> <figure class="ico delivery"></figure>
			<figcaption>
				Доставка
			</figcaption> </a>
		</div>

		<div class="item">
			<a href="page/cooperation"> <figure class="ico cooperation"></figure>
			<figcaption>
				Сотрудничество
			</figcaption> </a>
		</div>

	</div>
</section>
<%= render partial: 'order' %>
<%= render partial: 'factories' %>
<%= render partial: 'news' %>
<%= render partial: 'map' %>