config/routes.rb
Rails.application.routes.draw do
  get 'news/index'

  mount Ckeditor::Engine => '/ckeditor'
  mount Rich::Engine => '/rich', :as => 'rich'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'welcome#index'
  
  get 'jobs' => 'pages#jobs'
  resources :jobs, only: [:show]
  resources :feedbacks
  resources :pages, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :deliveries
  post '/delivery/get_price' => 'deliveries#get_price', as: :get_price
  resources :news, only: [:index, :show]
  get 'contacts' => 'pages#contacts'
  get 'delivery' => 'pages#delivery'
  
  get 'products' => 'pages#products'
  get 'page/:id' => 'pages#show'
  
  get 'factories' => 'factories#index', as: :factories
  get 'factory/:id' => 'factories#show', as: :factory

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    can :manage, :all
    can :import, [Delivery]
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  def before_import_save(record)
  end
end

app/models/factory_oil.rb
class FactoryOil < ActiveRecord::Base
  has_many :product_relations
  has_many :products, :through => :product_relations
  validates :name, :fullname, :about, :address, :image, presence: true
  scope :active, -> { where is_active: true }
  scope :on_main, -> { where is_main: true }

  DEFAULT_AVATAR = 'demo/_blank.png'
  has_attached_file :image,
                    styles: { small: '250x150>', medium: '220x280#', thumb: '100x125#' },
                    default_url: DEFAULT_AVATAR,
                    url: '/system/:class/:id/:style/:basename.:extension',
                    path: ':rails_root/public/system/:class/:id/:style/:basename.:extension'

  validates_attachment_content_type :image, content_type: /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :text, presence: true
  scope :active, -> { where is_active: true }
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  def type_of
    [['Главное меню', 0],['Меню подвала',1]]
  end
end

app/models/news.rb
class News < ActiveRecord::Base
  validates :title, :announce, presence: true
  scope :active, -> { where is_active: true }

end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :name, :uri, :text, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  has_many :product_relations
  has_many :factory_oils, :through => :product_relations
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  
  def before_import_save(record)
    p record
    p "------" 
    
    if !ProductCategory.exists?(name: record[:product_category])
      ProductCategory.create name: record[:product_category], is_active: true
    end
  end
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  validates :name, presence: true
  scope :active, -> { where is_active: true }  
  has_many :products, dependent: :destroy
end

app/models/product_relation.rb
class ProductRelation < ActiveRecord::Base
  belongs_to :product
  belongs_to :factory_oil
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  
  add_breadcrumb "Вакансии", :jobs_path

  def show
    @job = Job.find params[:id]
    add_breadcrumb @job.title if @job

  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  
  add_breadcrumb "Новости компании", :news_index_path
  def index
    @news = News.all.active.order('created_at desc')
  end
  def show
    @news = News.find_by_id! params[:id]
    add_breadcrumb @news.title if @news
  end 
  private
   def news_params
      params.require(:news).permit(:created_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_main_menu
    menu = Page.find_by_uri(:main_menu)
    menu.text.html_safe if menu
  end
  def get_footer_menu
    footer = Page.find_by_uri(:footer_menu)
    footer.text.html_safe if footer
  end
  def setting
    Setting.first! 
  end
end

app/helpers/deliveries_helper.rb
module DeliveriesHelper

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
      <img class="logo-footer" src="/assets/logo.png"/>
      <nav class="footer-menu">
        <%= get_main_menu() %>
      </nav>
    <div class="phone-container">
      <figure class="ico phone-ico"></figure>
      <span class="phone"><%= setting.footer_phone %></span>
    </div>  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
	<div class="header-top">
		<nav class="header-menu">
			<%= get_main_menu() %>
		</nav>
		<%= link_to image_tag("logo.png"), root_path(), class: "logo-main" %>
		<div class="feedback-container">
			<a class="feedback-button btn2" href="#">Заказать звонок</a>
			<%= render partial: 'layouts/popup_callback' %>
		</div>		
		<div class="phone">
			+7(843)235-01-01
		</div>
	</div>
</header>

app/views/layouts/_header_page.html.erb
<header class="header header-page">
	<div class="header-top">
		<%= link_to image_tag("logo-blue.png"), root_path(), class: "logo-main" %>
		<nav class="header-menu">
			<%= get_main_menu() %>
		</nav>
		<div class="feedback-container">
			<a class="feedback-button btn2" href="#">Заказать звонок</a>
			<%= render partial: 'layouts/popup_callback' %>
		</div>		
		<div class="phone">
			<%= setting.header_phone %>
		</div>
	</div>
</header>
<div class="clear"></div>
<div class="breadcrumbs">
	<div class="wrap">
		<%= render_breadcrumbs :separator => "<span></span>" %>
	</div>
</div>

app/views/layouts/_popup_callback.html.erb
<div class="popup-form popup-callback">
  <div class="title">Мы вам перезвоним!</div>
  <%= form_for Feedback.new, remote: true  do |f| %>
      <%= f.hidden_field :title, value: :order_call %>
      <div class="form">
        <div class="submit_status notice"></div>

        <div class="line">
          <label>Введите имя</label>
          <%= f.text_field :from, class: 'inp-text', autofocus: true, required: true%>
        </div>
        <div class="line">
          <label>Введите телефон</label>
          <%= f.text_field :phone, class: 'inp-text', autofocus: true, required: true%>
        </div>
        <div class="line line-send">
          <%= f.submit "Заказать звонок", class: "btn" %>
          <span>Ваши данные в безопасности</span>
        </div>
      </div>
  <% end %>
  <a href="#" class="close"></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="">
-->
<!--[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="">
-->
<!--[if IE 8] <html class="no-js lt-ie9" lang="">
-->
<!-- [if gt IE 8]><!
-->
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
    <title>ООО Тритон Трейд | Доставка топлива оптом</title>
    <meta name="description" content="<%= setting.description %>"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <link href="apple-touch-icon.png" rel="apple-touch-icon"/>
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
</head>
<body itemscope="" itemtype="http://schema.org/WebPage">
<section id="container">
  <%= render :partial => params[:controller]=='welcome' ? 'layouts/header' : 'layouts/header_page' %>
  <%= yield %>
  <div class="empty padding"></div>
</section>
<%= render :partial => 'layouts/footer' %>
<div class="shadow-fixed"></div>
</body>

</html>

app/views/pages/contacts.html.erb
<script src="http://api-maps.yandex.ru/2.0/?load=package.full&lang=ru-RU" type="text/javascript"></script>
<script>
	ymaps.ready(function() {
		var myMap = new ymaps.Map('map', {
			center : [55.83163901429401, 49.18854214547718],
			zoom : 16
		}),
		    myPlacemark = new ymaps.Placemark([55.83160882223887, 49.195623177276495], {
			hintContent : 'ООО Тритон Трейд'
		}, {
			iconLayout : 'default#image',
			// Своё изображение иконки метки.
			iconImageHref : '/assets/marker.png',
			// Размеры метки.
			iconImageSize : [150, 150],
			// Смещение левого верхнего угла иконки относительно
			// её "ножки" (точки привязки).
			iconImageOffset : [-75, -75]
		});
		myMap.geoObjects.add(myPlacemark);
	}); 
</script>
<div class="wrap contact-wrap">
	<div class="contact">
		<h1>Контактная информация</h1>
		<ul>
			<li>
				<p>
					420000, Республика Татарстан
					<br>
					г.Казань, ул.Журналистов д.62, оф. 319
					<br>
					Бизнес-центр "Супер Бизнес Центр".
				</p>
			</li>
			<li>
				<p>Отдел продаж: <br/> <strong>8(843) 231-22-21 </strong></p>
				<p>Отдел сопровождения: <br/> <strong>8(843) 231-22-22 </strong></p>
				<p>Юридический отдел: <br/> <strong>8(843) 231-22-24 </strong></p>
			</li>
			<li>
				<a href="#">info@tritontrade.ru</a>
			</li>
			<li>
				Работаем по будням <%= setting.work_time %>
			</li>
		</ul>
	</div>
	<!-- /.contact -->
</div>
<div id="map"></div>
<div class="padding15"></div>
<div class="wrapper">
	<div class="wrap">
	<div class="contact-person">
		<div class="contact-person-in">
			<div class="contact-person-info">	
				<h1>Руководство компании</h1>			
				<div class="contact-person-item">					
					<div class="contact-person-item-name">
						Фазуллин Ренат Ильфатович
					</div>
					<div class="contact-person-item-post">
						Генеральный директор
					</div>
					<p>
						тел. 
						<a href="#" class="contact-person-item-phone"> 
							8(843)231-22-22
						</a>
					</p>
					<p>
						<a href="#">info@tritontrade.ru</a>
					</p>
				</div>
			</div>

		</div>
	</div>
	<div class="separator"></div>
	<div class="contact-person">
		<div class="contact-person-in">
			<div class="contact-person-info">		
				<h1>Отдел продаж</h1>	
				<div class="contact-person-item">					
					<div class="contact-person-item-name">
						Иванова Регина Николаевна
					</div>
					<div class="contact-person-item-post">
						Руководитель отдела
					</div>
					<p>
						тел. 
						<a href="#" class="contact-person-item-phone"> 
							8(843)231-22-21
						</a>
					</p>
					<p>
						<a href="#">info@tritontrade.ru</a>
					</p>
				</div>
				<div class="contact-person-item">					
					<div class="contact-person-item-name">
						Вафин Тимур Ильгизарович
					</div>
					<div class="contact-person-item-post">
						Ведущий специалист
					</div>
					<p>
						тел. 
						<a href="#" class="contact-person-item-phone"> 
							8(843)231-22-23
						</a>
					</p>
					<p>
						<a href="#">info@tritontrade.ru</a>
					</p>
				</div>
				<div class="contact-person-item">					
					<div class="contact-person-item-name">
						Агафонов Александр Владимирович
					</div>
					<div class="contact-person-item-post">
						Ведущий специалист отдела сопровождения
					</div>
					<p>
						тел. 
						<a href="#" class="contact-person-item-phone"> 
							8(843)231-22-23
						</a>
					</p>
					<p>
						<a href="#">info@tritontrade.ru</a>
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="separator"></div>
	<div class="contact-person">
		<div class="contact-person-in">
			<div class="contact-person-info">	
				<h1>Юридический отдел</h1>			
				<div class="contact-person-item">					
					<div class="contact-person-item-name">
						Загидуллин Ильфат Ильфатович
					</div>
					<div class="contact-person-item-post">
						Руководитель отдела
					</div>
					<p>
						тел. 
						<a href="#" class="contact-person-item-phone"> 
							8(843)231-22-22
						</a>
					</p>
					<p>
						<a href="info@tritontrade.ru">info@tritontrade.ru</a>
					</p>
				</div>
			</div>

		</div>
	</div>
	
	</div>
</div>

app/views/pages/delivery.html.erb
<div class="wrap padding15">
	<h1>Доставка</h1>
</div>

app/views/pages/jobs.html.erb
<div class="clear"></div>
<div class="job">	
	<div class="wrap job-container">
		<div class="job-info">
			<div class="dg-job-header-work-slogon">
				Карьера
				<br/>
				в Тритон Трейд
			</div>
			<div class="dg-job-header-slogon cufon">
				<span class="blue"> Наша команда всегда рада </span>
				<br>
				<span class="blue"> новым интересным людям </span>
				<br>
				<span class="blue"> и настоящим профессионалам! </span>
			</div>
		</div>
	</div>
</div>
<div class="wrap">
	<div class="dg-job-page-content">
		<div class="dg-job-left-content padding15">
			<h1 class="dg-job-title cufon"> Если вы </h1>
			<ul class="dg-job-default-list">
				<li>
					нацелены  на успех;
				</li>
				<li>
					умеете решать задачи не только творчески, но также быстро и в срок;
				</li>
				<li>
					накопили большой  потенциал или опыт,
				</li>
			</ul>
			<h1 class="dg-job-title cufon"> то мы предлагаем вам </h1>
			<ul class="dg-job-default-list">
				<li>
					постоянное движение вперед и развитие,
				</li>
				<li>
					а также место, где можно остановиться и перекусить;
				</li>
				<li>
					работу над интересными проектами,
				</li>
				<li>
					разумеется, за достойное вознаграждение,
				</li>
				<li>
					демократичное общение с коллегами
				</li>
				<li>
					и руководителями, которые прислушиваются к вашему мнению и поощряют инициативу;
				</li>
				<li>
					и все это в уютном и современном офисе города Казани,
				</li>
				<li>
					где есть все, что нужно для работы,
				</li>
				<li>
					свежий кофе и чай в ассортименте.
				</li>
			</ul>
		</div>
		<div class="dg-job-right-content padding15">
			<h1 class="dg-job-title cufon">Наши вакансии</h1>
			<ul class="dg-job-default-list">
				<% @jobs.each do |j| %>
				<%= link_to j.title, job_path(j.id), remote: true %>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<div class="popup-form job-popup">

</div>

app/views/pages/show.html.erb
<div class="wrap padding15">
	<h1><%= @page.name %> </h1>
	<div class="content">
		<%= @page.text.html_safe %>
	</div>
</div>
<div class="clear"></div>